language: python

python:
  - "2.7"

install:
   - sudo apt-get install libmysqlclient-dev
   - sudo apt-get install python-dev
   - sudo pip install --upgrade pip
   - sudo pip install MySQL-python
   - sudo pip install Flask
   - sudo pip install nose
   - sudo pip install -r requirements.txt

script:       # script para tests
   - nosetests python_test.py
